method: local_kg

out_dir: './experiments/rl_experiments/hopper/local_kg'  # Directory for experiment results.

environment_name: Hopper-v1
mlp:
    layers: [11,3]
    discretize: 
    add_bias: False
    state_normalization: False
    manipulate_reward:
        shift: 1
        scale: 200

trials: 3
# Either choose max_iterations or max_objective_calls unequal None.
max_iterations: 300
max_objective_calls: 

optimizer_config:
    Model: derivative_gp
    model_config:
        prior_mean: 0.
        ard_num_dims: dim_search_space  # If not None, each input dimension gets its own separate lengthscale.
        N_max: 200
        lengthscale_constraint:
            constraint:
            kwargs:
        lengthscale_hyperprior:
            prior: gamma
            kwargs:
                concentration: 2.5
                rate: 20
        outputscale_constraint:
            constraint: greather_than
            kwargs:
                lower_bound: 0.001
        outputscale_hyperprior:
            prior: normal
            kwargs:
                loc: 2.
                scale: 1.
        noise_constraint:
            constraint:
            kwargs:
        noise_hyperprior:
            prior:
            kwargs:
    hyperparameter_config:
        optimize_hyperparameters: True
        hypers:
            covar_module.base_kernel.lengthscale:
            covar_module.outputscale:
            likelihood.noise: .02
        no_noise_optimization: True
    acqf_config: 
        num_fantasies: 256
    delta: 0.2
    optimize_acqf: opt_kg
    optimize_acqf_config: 
        q: 10
        num_restarts: 5
        raw_samples: 64
    bounds: 
        lower_bound: 
        upper_bound: 
    explore_interval: 1
    optimize_inner_acqf_config:
        q: 1
        num_restarts: 64
        raw_samples: 256
        bounds: 
            lower_bound: -1.0
            upper_bound: 1.0
    generate_initial_data:
    verbose: False
